/** English for the staff console (core), keyed by the Thai text. `{0}`, `{1}` … are filled in by t(). */
export const EN_CORE: Record<string, string> = {
  'ภาพรวมระบบ': 'Overview',
  'สถานีวิทยุ': 'Radio stations',
  'บันทึกระบบ': 'Logs',
  'งานเบื้องหลัง': 'Background jobs',
  'ผู้ใช้': 'Users',
  'ตั้งค่าแอป': 'App config',
  'ประวัติการแก้ไข': 'Audit trail',
  'ธีม': 'Theme',
  'เลือกธีมหน้าทีมงาน': 'Choose the staff console theme',
  'ออกจากระบบ': 'Sign out',
  'เวลาประเทศไทย': 'Thailand time',
  'ค้นหาสถานี…': 'Search stations…',
  'ค้นหาสถานี': 'Search stations',
  'เมนู': 'Menu',
  'บัญชี': 'Account',
  'การตั้งค่าของฉัน': 'My settings',
  'หมดเวลาเมื่อไม่ใช้งาน 30 นาที': 'Signs out after 30 minutes idle',
  'ตั้งค่าของฉัน': 'My settings',
  'ขยายเมนู': 'Expand menu',
  'ยุบเมนู': 'Collapse menu',
  'รอตรวจ {0}': '{0} awaiting review',
  'โหมดสี': 'Color mode',
  'เชื่อมต่อ API แล้ว': 'API connected',
  'โหลดข้อมูลสรุปไม่ได้': "Couldn't load the summary",
  'จัดการแค็ตตาล็อกสถานีวิทยุที่แอปจะเห็น': 'Manage the radio station catalog the apps see',
  'แอปเห็นอยู่': 'Visible in apps',
  '{0} สถานี': '{0} stations',
  'รอตรวจ': 'Awaiting review',
  'ระบบไม่พร้อมใช้งานชั่วคราว': 'The system is temporarily unavailable',
  'บัญชีนี้ไม่มีสิทธิ์เข้าหน้าทีมงาน': "This account can't open the staff console",
  'ลองโหลดหน้านี้อีกครั้งภายหลัง': 'Try loading this page again later.',
  'ถ้าคุณเป็นทีมงาน ให้ขอสิทธิ์จากผู้ดูแลระบบ': "If you're on the team, ask an admin for access.",
  'ไปที่การตั้งค่าของฉัน': 'Go to my settings',
  'รหัสยืนยันตัวตน (TOTP) ของบัญชีนี้มีการเปลี่ยนแปลง': "This account's one-time code (TOTP) has changed",
  'ระบบพักสิทธิ์ทีมงานไว้ก่อน ถ้าคุณเพิ่งตั้งรหัสใหม่เอง ให้แจ้งผู้ดูแลระบบเพื่อยืนยันกับคุณแล้วลงทะเบียนรหัสใหม่ ถ้าไม่ได้ตั้งเอง ให้เปลี่ยนรหัสผ่านและแจ้งผู้ดูแลระบบทันที':
    "Staff access is paused. If you just set up a new code yourself, ask an admin to confirm it with you and register it. If you didn't, change your password and tell an admin now.",
  'หน้าทีมงานต้องเข้าสู่ระบบด้วย MFA': 'The staff console needs an MFA sign-in',
  'เข้าสู่ระบบอีกครั้งพร้อมรหัสยืนยันตัวตนแบบใช้ครั้งเดียว แล้วระบบจะพากลับมาที่หน้านี้': "Sign in again with a one-time verification code and you'll be brought back to this page.",
  'เข้าสู่ระบบด้วย MFA': 'Sign in with MFA',
  'ขั้นตอนนี้ต้องยืนยันตัวตนด้วย MFA ภายใน 5 นาทีที่ผ่านมา ยังไม่ได้ทำรายการ': 'This step needs an MFA check within the last 5 minutes. Nothing was done.',
  'ยืนยัน MFA แล้วกลับมาหน้านี้': 'Verify with MFA and come back here',
  'เหตุผลต้องยาว 10–500 ตัวอักษร': 'The reason must be 10–500 characters.',
  'ตัวกรองไม่ถูกต้อง แก้แล้วค้นหาใหม่ก่อนส่งออก': "The filters aren't valid. Fix them and search again before exporting.",
  'ผลการค้นหาเกิน 10,000 {0} กรุณาแคบช่วงเวลาหรือเพิ่มตัวกรอง': 'The search returns more than 10,000 {0}. Narrow the time range or add filters.',
  'หมดเวลาเข้าใช้งาน กรุณาเข้าสู่ระบบอีกครั้ง': 'Your session expired. Please sign in again.',
  'ระบบไม่พร้อมใช้งานชั่วคราว ลองอีกครั้งภายหลัง': 'The system is temporarily unavailable. Try again later.',
  'ดาวน์โหลด {0} แล้ว การส่งออกนี้ถูกบันทึกพร้อมเหตุผล': 'Downloaded {0}. This export was recorded with its reason.',
  'ส่งออก CSV': 'Export CSV',
  'เหตุผลในการส่งออก (จะถูกบันทึกไว้)': 'Reason for the export (recorded)',
  'ส่งออกตามตัวกรองที่ใช้อยู่ สูงสุด 10,000 {0}': 'Exports the current filters, up to 10,000 {0}',
  'กำลังส่งออก…': 'Exporting…',
  'ดาวน์โหลด CSV': 'Download CSV',
  'ยกเลิก': 'Cancel',
  'ซัพพอร์ต': 'Support',
  'บรรณาธิการแค็ตตาล็อก': 'Catalog editor',
  'โอเปอเรเตอร์': 'Operator',
  'แอดมิน': 'Admin',
  'ผู้ตรวจสอบ': 'Auditor',
  'ร่าง': 'Draft',
  'เผยแพร่แล้ว': 'Published',
  'ปิดอยู่': 'Disabled',
  'ทั้งหมด': 'All',
  'ต้องเป็นแอดมินจึงจะเผยแพร่ได้': 'Only an admin can publish',
  'คุณแก้ร่างนี้เอง ต้องให้แอดมินคนอื่นเป็นผู้เผยแพร่': 'You edited this draft yourself; another admin has to publish it',
  'เวอร์ชันนี้เผยแพร่อยู่แล้ว': 'This version is already published',
  'ยังไม่มีหลักฐานสิทธิ์ที่ใช้งานอยู่': 'No active rights evidence yet',
  'หลักฐานสิทธิ์ไม่ครอบคลุมประเทศของสถานี': "The rights evidence doesn't cover the station's country",
  'หลักฐานสิทธิ์ยังไม่ถึงวันเริ่มใช้': "The rights evidence hasn't started yet",
  'สิทธิ์หมดอายุแล้ว': 'Rights have expired',
  'มีสิทธิ์ใช้งานอยู่': 'Rights in place',
  'ยังไม่มีข้อมูลสิทธิ์': 'No rights on record',
  'สิทธิ์ไม่ครอบคลุมประเทศนี้': "Rights don't cover this country",
  'สิทธิ์ยังไม่เริ่ม': 'Rights not started yet',
  'ใช้งานอยู่': 'Active',
  'ยังไม่ถึงวันเริ่ม': 'Scheduled',
  'หมดอายุ': 'Expired',
  'เพิกถอนแล้ว': 'Revoked',
  'ได้รับอนุญาตจากเจ้าของสถานี': 'Permission from the station owner',
  'ตามเงื่อนไขของผู้แพร่ภาพ': "Broadcaster's terms",
  'ผ่านผู้รวบรวมที่มีใบอนุญาต': 'Through a licensed aggregator',
  'สตรีมสาธิตของเราเอง': 'Our own demo stream',
  'ชื่อสถานี': 'Station name',
  'ประเทศ': 'Country',
  'ภาษา': 'Language',
  'แนวเพลง': 'Genres',
  'ลิงก์สตรีม': 'Stream URL',
  'รูปแบบเสียง': 'Audio format',
  'บิตเรต (kbps)': 'Bitrate (kbps)',
  'เหตุผล': 'Reason',
  'เจ้าของสิทธิ์': 'Rights holder',
  'ที่มาของสิทธิ์': 'Basis',
  'เลขอ้างอิงหลักฐาน': 'Evidence reference',
  'ประเทศที่ครอบคลุม': 'Territories',
  'เริ่มใช้': 'Valid from',
  'สิทธิ์หมดอายุ': 'Expires',
  'รหัสไฟล์หลักฐาน': 'Evidence file keys',
  'เหตุผลที่เพิกถอน': 'Reason for revoking',
  'ต้องกรอก': 'Required',
  'ความยาวไม่ถูกต้อง': 'Wrong length',
  'มีอักขระที่ไม่อนุญาต': "Contains characters that aren't allowed",
  'ไม่ใช่ลิงก์ที่ถูกต้อง': 'Not a valid URL',
  'ต้องเป็นลิงก์ https เท่านั้น': 'Must be an https URL',
  'ห้ามใส่ชื่อผู้ใช้หรือรหัสผ่านในลิงก์': 'No username or password in the URL',
  'ห้ามมี # ในลิงก์': 'No # in the URL',
  'ใช้ชื่อโดเมน ห้ามใช้เลข IP': 'Use a domain name, not an IP address',
  'โดเมนนี้เป็นเครือข่ายภายใน': 'This domain is on an internal network',
  'ใช้พอร์ต 443 เท่านั้น': 'Port 443 only',
  'ใช้รหัสประเทศ 2 ตัวอักษรพิมพ์ใหญ่ เช่น TH': 'Use a 2-letter uppercase country code, e.g. TH',
  'ใช้รหัสภาษา 2–3 ตัวอักษรพิมพ์เล็ก เช่น th': 'Use a 2–3 letter lowercase language code, e.g. th',
  'ไม่เกิน 5 แนว': 'At most 5 genres',
  'ใช้ a-z, 0-9 และ - เท่านั้น': 'Use a-z, 0-9 and - only',
  'ค่าที่เลือกไม่อนุญาต': "That value isn't allowed",
  'ค่าเกินช่วงที่รับได้ (8–512)': 'Out of range (8–512)',
  'วันที่ไม่ถูกต้อง': 'Invalid date',
  'สั้นเกินไป อธิบายอย่างน้อย 20 ตัวอักษร': 'Too short; explain in at least 20 characters',
  'วันหมดอายุต้องไม่ก่อนวันเริ่มใช้': "The expiry can't be before the start date",
  'ใช้รหัสไฟล์ในที่เก็บส่วนตัว ห้ามใส่ลิงก์': 'Use a private storage file key, not a link',
  'ไม่เกิน 10 รายการ': 'At most 10 items',
  'ช่องนี้ไม่รองรับแล้ว': 'This field is no longer supported',
  'สิทธิ์ถึง {0}': 'Rights until {0}',
  'สิทธิ์ไม่มีวันหมดอายุ': 'Rights never expire',
  'ไทย': 'Thai',
  'อังกฤษ': 'English',
  'ญี่ปุ่น': 'Japanese',
  'จีน': 'Chinese',
  'เกาหลี': 'Korean',
  'ลาว': 'Lao',
  'พม่า': 'Burmese',
  'เขมร': 'Khmer',
  '15 นาทีล่าสุด': 'Last 15 minutes',
  '1 ชั่วโมงล่าสุด': 'Last hour',
  '6 ชั่วโมงล่าสุด': 'Last 6 hours',
  '24 ชั่วโมงล่าสุด': 'Last 24 hours',
  'ทุกระดับ': 'All levels',
  'เฉพาะ ERROR': 'ERROR only',
  'WARN ขึ้นไป': 'WARN and above',
  'ช่วงเวลา': 'Time range',
  'ระดับ': 'Level',
  'รหัสเหตุการณ์': 'Event code',
  'รหัสข้อผิดพลาด': 'Error code',
  'หน้าถัดไป': 'Next page',
  '7 วันล่าสุด': 'Last 7 days',
  '30 วันล่าสุด': 'Last 30 days',
  '90 วันล่าสุด': 'Last 90 days',
  'สร้างร่างสถานี': 'Created station draft',
  'แก้ร่างสถานี': 'Edited station draft',
  'เผยแพร่สถานี': 'Published station',
  'เผยแพร่สถานีแบบฉุกเฉิน (ไม่มีผู้ตรวจคนที่สอง ต้องตรวจย้อนหลัง)': 'Emergency station publish (no second reviewer; needs follow-up review)',
  'ปิดสถานี': 'Disable station',
  'เปิดสถานีอีกครั้ง': 'Re-enable station',
  'ตรวจสตรีม': 'Checked stream',
  'เพิ่มหลักฐานสิทธิ์สถานี': 'Added station rights evidence',
  'เพิกถอนสิทธิ์สถานี': 'Revoked station rights',
  'ให้สิทธิ์ทีมงาน': 'Granted staff role',
  'ถอนสิทธิ์ทีมงาน': 'Revoked staff role',
  'ค้นบันทึกระบบ': 'Searched logs',
  'ส่งออกบันทึกระบบ': 'Exported logs',
  'ดูประวัติการแก้ไข': 'Viewed audit trail',
  'ผู้ใช้ออกจากระบบอุปกรณ์': 'User signed out a device',
  'ส่งออกประวัติ': 'Exported audit trail',
  'ผู้ใช้ดาวน์โหลดข้อมูล': 'User downloaded their data',
  'ผู้ใช้ขอลบบัญชี': 'User requested account deletion',
  'ลบบัญชีซ้ำหลังกู้ข้อมูล': 'Re-deleted account after a restore',
  'ลูกค้าสร้างรหัสให้ support': 'Customer created a support code',
  'support ได้สิทธิ์ดูรายงานวินิจฉัย': 'Support got access to diagnostics',
  'รหัสจากลูกค้าใช้ไม่ได้': 'Customer code was rejected',
  'ลูกค้ายกเลิกสิทธิ์ support': 'Customer revoked support access',
  'support เปิดดูรายงานวินิจฉัย': 'Support opened diagnostics',
  'ลบข้อมูลบัญชีเสร็จ': 'Account data deleted',
  'สั่งงานเบื้องหลังซ้ำ': 'Retried background job',
  'เปิดดูข้อมูลผู้ใช้': 'Looked up user',
  'แก้ร่างตั้งค่าแอป': 'Edited app config draft',
  'เผยแพร่ตั้งค่าแอป': 'Published app config',
  'ย้อนตั้งค่าแอป': 'Rolled back app config',
  'ทุกการกระทำ': 'All actions',
  'สถานี': 'Station',
  'สิทธิ์สถานี': 'Station rights',
  'สิทธิ์ทีมงาน': 'Staff roles',
  'การค้นบันทึก': 'Log searches',
  'การดูประวัติ': 'Audit views',
  'ผู้กระทำ': 'Actor',
  'การกระทำ': 'Action',
  'เป้าหมาย': 'Target',
  'โอเปอเรเตอร์ {0}': 'Operator {0}',
  'ช่อง: {0}': 'Fields: {0}',
  'บทบาท: {0}': 'Role: {0}',
  'แทน r{0}': 'replaces r{0}',
  'ตรวจสตรีมของร่าง': 'Checked the draft stream',
  'ตรวจสตรีมที่เผยแพร่': 'Checked the published stream',
  'ผล: {0}': 'Result: {0}',
  'ทำรายการถี่เกินไป รอประมาณหนึ่งนาทีแล้วลองใหม่': 'Too many requests. Wait about a minute and try again.',
  'ยังไม่ได้ตรวจ': 'Not checked yet',
  'ตรวจไม่ผ่าน': 'Failed check',
  'น่าสงสัย': 'Suspect',
  'ที่อยู่สตรีมไม่ถูกต้อง': 'Invalid stream address',
  'หาโดเมนไม่เจอ': 'Domain not found',
  'ชี้ไปที่อยู่ภายในหรือไม่ใช่สาธารณะ': 'Points to an internal or non-public address',
  'ไม่ตอบภายใน 10 วินาที': 'No answer within 10 seconds',
  'เชื่อมต่อไม่ได้': "Couldn't connect",
  'เซิร์ฟเวอร์ตอบข้อผิดพลาด': 'Server returned an error',
  'เปลี่ยนเส้นทางเกิน 3 ครั้ง': 'More than 3 redirects',
  'ไม่ใช่สตรีมเสียง': 'Not an audio stream',
  '{0} ครั้งติด': '{0} in a row',
};
