/** English for the staff console (ops), keyed by the Thai text. `{0}`, `{1}` … are filled in by t(). */
export const EN_OPS: Record<string, string> = {
  'โลโก้ TuneDeck สำหรับสถานีที่ไม่มีโลโก้': 'TuneDeck logo for stations without one',
  'แสดงบนแผนที่และในรายการแทนสถานีที่ไม่มีโลโก้ของตัวเอง เปลี่ยนแล้วมีผลภายในไม่กี่นาที': 'Shown on the map and in lists for stations with no logo of their own. A change shows within a few minutes.',
  'โลโก้ที่แอดมินอัปโหลด': 'Logo uploaded by an admin',
  'โลโก้มาตรฐานของ TuneDeck': 'The standard TuneDeck logo',
  'อัปโหลดโลโก้ใหม่': 'Upload a new logo',
  // Overview (/admin/overview)
  '1 ชั่วโมง': '1 hour',
  '24 ชั่วโมง': '24 hours',
  '7 วัน': '7 days',
  'API ตอบ error บ่อย': 'API errors are frequent',
  '{0} คำขอจบด้วย 5xx เกิน 5% ของทั้งหมด': '{0} requests ended in 5xx, over 5% of all requests',
  'ลบบัญชีไม่สำเร็จ': 'Account deletion failed',
  '{0} คำขอลบไม่สำเร็จ (กำลังลองใหม่หรือรอทีมงาน) ดูบันทึก ACCOUNT_PURGE_FAILED': '{0} deletion requests failed (retrying or waiting for staff). See the ACCOUNT_PURGE_FAILED log',
  'ลบบัญชีใกล้เกินกำหนด 30 วัน': 'Account deletion near the 30-day deadline',
  '{0} คำขอค้างนานกว่า 25 วัน': '{0} requests waiting more than 25 days',
  'คิวลบบัญชีค้าง': 'Account deletion queue is stuck',
  '{0} คำขอถึงรอบแล้วแต่ยังไม่ได้ทำเกิน 5 นาที': '{0} requests due but not run for over 5 minutes',
  'คิวส่งออกข้อมูลค้าง': 'Data export queue is stuck',
  'คิวปิดเซสชัน Keycloak ค้าง': 'Keycloak session end queue is stuck',
  '{0} รายการถึงรอบแล้วแต่ยังไม่ได้ทำเกิน 5 นาที': '{0} items due but not run for over 5 minutes',
  'งานเบื้องหลังรอทีมงาน': 'Background jobs waiting for staff',
  '{0} งานลองครบ 5 ครั้งแล้วไม่สำเร็จ ต้องสั่งลองใหม่': '{0} jobs failed all 5 attempts and need a manual retry',
  'API ตอบช้า': 'API is slow',
  'p95 {0} ms เกิน 1 วินาที ใน 10 นาทีล่าสุด': 'p95 {0} ms, over 1 second in the last 10 minutes',
  'สถานีน่าสงสัย': 'Suspect stations',
  '{0} สถานีตรวจไม่ผ่าน 3 ครั้งติด รอแอดมินตรวจ': '{0} stations failed 3 checks in a row and wait for an admin',
  'ตัวตรวจสตรีมไม่ได้รัน': 'Stream checker is not running',
  'ไม่มีผลตรวจใหม่นานเกิน 2.5 รอบ': 'No new check results for over 2.5 rounds',
  'สิทธิ์เผยแพร่ใกล้หมด': 'Station rights ending soon',
  'ไม่มี backup ใหม่': 'No recent backup',
  'backup ล่าสุดเมื่อ {0} ชั่วโมงก่อน เกิน 24 ชั่วโมง ตรวจงาน backup.sh': 'Last backup {0} hours ago, over 24 hours; check the backup.sh job',
  '{0} รายงานจาก {1} เครื่อง · {2} เหตุการณ์': '{0} reports from {1} devices · {2} events',
  '{0} ล่าสุด · เฉพาะผู้ที่ยินยอมส่ง': 'Last {0} · only people who agreed to send',
  '{0} เหตุการณ์ · ล้มเหลว {1}': '{0} events · {1} failed',
  'ซื้อ Pro': 'Pro purchase',
  'นำเข้าสำเร็จ': 'Import completed',
  'นำเข้าไม่สำเร็จ': 'Import failed',
  'ยังไม่มีรายงานจากแอปในช่วงนี้ (แอปส่งเฉพาะเมื่อผู้ใช้ยินยอม)': 'No app reports in this window (the app sends them only with the user’s consent)',
  'รหัสปัญหา': 'Failure code',
  'รหัสปัญหาที่พบบ่อยสุด': 'Most common failure codes',
  'รายงานจากแอป': 'App diagnostics',
  'รุ่นที่ส่งมากสุด': 'Busiest builds',
  'ล้มเหลว': 'Failed',
  'ล้มเหลว {0}/{1}': '{0}/{1} failed',
  'เริ่มเล่น': 'Playback start',
  'เล่นต่อได้': 'Recovered',
  'เสียงสะดุด': 'Stall',
  'เหตุการณ์จากแอปและสัดส่วนที่ล้มเหลว': 'App events and how many failed',
  'แอปผิดพลาด': 'App error',
  '{0} สถานีสิทธิ์จะหมดใน 14 วัน ต้องเพิ่มหลักฐานใหม่ ไม่อย่างนั้นจะหายจากแอป': '{0} stations have rights ending within 14 days; add new evidence or they leave the apps',
  'ไม่มีคำขอเข้ามาเลย': 'No requests coming in',
  'ไม่มีคำขอใน 15 นาทีล่าสุด ตัวเลขอาจไม่ใช่สถานะตอนนี้': 'No requests in the last 15 minutes; the figures may not reflect the current state',
  'ตั้งแต่ {0}': 'since {0}',
  'สำเร็จและ 4xx': 'Success and 4xx',
  'สูงสุด {0} คำขอต่อช่อง': 'Peak {0} requests per bar',
  'คำขอ API ใน {0} ล่าสุด แยกช่องละช่วงเวลา': 'API requests in the last {0}, one bar per interval',
  '{0} คำขอ': '{0} requests',
  'ตอนนี้': 'Now',
  'คำขอ API ต่อช่วงเวลา': 'API requests per interval',
  'เริ่ม': 'Start',
  'คำขอ': 'Requests',
  'ไม่มีเรื่องที่ต้องดูตอนนี้': 'Nothing needs attention right now',
  'เรื่องที่ต้องดู': 'Needs attention',
  'วิกฤต: ': 'Critical: ',
  'เตือน: ': 'Warning: ',
  'ดู': 'View',
  'คำขอ API': 'API requests',
  'ไม่มีคำขอใน 15 นาทีล่าสุด': 'No requests in the last 15 minutes',
  'ล่าสุด {0}': 'Latest {0}',
  'อัตรา 5xx': '5xx rate',
  'จาก {0} คำขอ ยังน้อยเกินจะสรุป': 'Of {0} requests, too few to tell',
  '{0} จาก {1} คำขอ': '{0} of {1} requests',
  'เวลาตอบ p95': 'p95 response time',
  'ค่ากลาง {0}': 'Median {0}',
  'สถานีที่เปิดอยู่': 'Published stations',
  'เล่นได้ {0} · ไม่ผ่าน {1} · น่าสงสัย {2} · ยังไม่ตรวจ {3}': 'Playable {0} · Failing {1} · Suspect {2} · Unchecked {3}',
  'คิวลบบัญชี': 'Account deletion queue',
  'ไม่สำเร็จ {0} · ต้องเสร็จใน {1} วัน': 'Failed {0} · Due within {1} days',
  'ต้องเสร็จใน {0} วัน': 'Due within {0} days',
  'ตัวตรวจสตรีม เปิดอยู่ ผลล่าสุด {0}': 'Stream checker on, last result {0}',
  'ตัวตรวจสตรีม ปิดอยู่ (STATION_CHECK_ENABLED)': 'Stream checker off (STATION_CHECK_ENABLED)',
  'ข้อมูล {0} ถึง {1}': 'Data for {0} up to {1}',
  'รายงานวินิจฉัย {0} ฉบับ': '{0} diagnostic reports',
  'ตัวเลขรวมเท่านั้น ไม่มีข้อมูลรายคน': 'Aggregates only, no per-person data',
  'ไม่มี 5xx ในช่วงนี้': 'No 5xx in this window',
  'เส้นทางที่ตอบ 5xx บ่อยสุด': 'Top 5xx routes',
  'เส้นทาง': 'Route',
  'สถานะ': 'Status',
  'ครั้ง': 'Count',
  'บัญชีนี้ไม่มีสิทธิ์ดูภาพรวมระบบ (ต้องเป็นโอเปอเรเตอร์หรือแอดมิน)': 'This account cannot view the system overview (operator or admin only)',
  'โหลดภาพรวมไม่ได้ในขณะนี้ ลองใหม่อีกครั้ง': 'Could not load the overview right now. Please try again',
  'ตัวเลขรวม {0}': 'Totals for {0}',
  'สัญญาณเตือน': 'Alerts',
  'ทุกช่องปกติ': 'All channels normal',
  'คำขอ {0} ครั้ง': '{0} requests',
  'สรุป {0} ล่าสุด ตัวเลขรวมเท่านั้น': 'Summary of the last {0}, aggregates only',
  '{0} คำขอ · 5xx {1}': '{0} requests · 5xx {1}',
  'สุขภาพสถานี': 'Station health',
  'คิวงานเบื้องหลัง': 'Background queues',
  'รายการภาพรวม': 'Overview items',
  'รายละเอียด': 'Details',
  'เล่นได้': 'Playable',
  'น่าสงสัย': 'Suspect',
  'ยังไม่ได้ตรวจ': 'Not checked yet',
  'คำขอลบบัญชีค้าง': 'Open account deletion requests',
  'ลบไม่สำเร็จ (ลองใหม่หรือรอทีมงาน)': 'Deletion failed (retrying or waiting for staff)',
  'รายงานวินิจฉัยในช่วงนี้': 'Diagnostic reports in this window',
  '{0} ล่าสุด · ตัวเลขรวมเท่านั้น': 'Last {0} · aggregates only',
  '{0} เรื่อง': '{0} items',

  // Background jobs (/admin/jobs)
  'ค้างอยู่': 'Open',
  'ไม่สำเร็จ': 'Failed',
  'รอทีมงาน': 'Waiting for staff',
  'เสร็จแล้ว (7 วัน)': 'Completed (7 days)',
  'ทั้งหมด': 'All',
  'รอทำ': 'Pending',
  'ไม่สำเร็จ กำลังลองใหม่อัตโนมัติ': 'Failed, retrying automatically',
  'ลองครบ 5 ครั้งแล้ว รอทีมงานสั่งลองใหม่': 'All 5 attempts used, waiting for staff to retry',
  'เสร็จแล้ว': 'Completed',
  'ลบบัญชีผู้ใช้': 'Account deletion',
  'ส่งออกข้อมูลบัญชี': 'Account data export',
  'ปิดเซสชัน Keycloak': 'Keycloak session end',
  'ลบข้อมูลบัญชีเสร็จแล้ว': 'Account data deleted',
  'สร้างไฟล์ส่งออกข้อมูลเสร็จแล้ว': 'Data export file created',
  'ปิดเซสชัน Keycloak แล้ว': 'Keycloak session ended',
  '{0} นาที': '{0} min',
  '{0} ชั่วโมง': '{0} h',
  '{0} วัน': '{0} days',
  'เสร็จ {0}': 'Completed {0}',
  'เลยกำหนด 30 วันแล้ว': 'Past the 30-day deadline',
  'หยุดลองแล้ว รอทีมงาน': 'Stopped, waiting for staff',
  'รอบถัดไป (ภายใน 1 นาที)': 'Next round (within 1 minute)',
  'รอทำ {0} · ลองใหม่ {1} · รอทีมงาน {2} · ค้างนานสุด {3}': 'Pending {0} · Retrying {1} · Waiting for staff {2} · Oldest {3}',
  'สถานะงาน': 'Job status',
  'กรอกเหตุผล 10–500 ตัวอักษร': 'Enter a reason of 10–500 characters',
  'บัญชีนี้ไม่มีสิทธิ์สั่งงานซ้ำ': 'This account cannot retry jobs',
  'หมดเวลาใช้งาน เข้าสู่ระบบใหม่แล้วลองอีกครั้ง': 'Your session expired. Sign in again and retry',
  'ระบบกำลังทำคิวนี้อยู่แล้ว รอสักครู่แล้วโหลดหน้าใหม่': 'This queue is already being processed. Wait a moment and reload the page',
  'สั่งลองใหม่งานนี้ครบ 3 ครั้งใน 24 ชั่วโมงแล้ว แก้สาเหตุก่อน แล้วรอให้ระบบลองเองหรือลองพรุ่งนี้': 'This job was retried 3 times in 24 hours. Fix the cause first, then let the system retry or try again tomorrow',
  'ผู้ใช้ขอส่งออกข้อมูลใหม่ไปแล้ว ไม่ต้องลองงานนี้อีก': 'The user has requested a new export; no need to retry this job',
  'ไม่พบงานนี้แล้ว': 'This job no longer exists',
  'สั่งงานไม่ได้ในขณะนี้ ลองใหม่อีกครั้ง': 'Could not start the job right now. Please try again',
  'ยังไม่สำเร็จ ลองครบ 5 ครั้งแล้ว ดูสาเหตุในบันทึก {0}': 'Still failing after all 5 attempts. See the {0} log for the cause',
  'ยังไม่สำเร็จ ระบบจะลองต่ออัตโนมัติ ดูสาเหตุในบันทึก {0}': 'Still failing; the system will keep retrying. See the {0} log for the cause',
  'เพิ่งลองไปเมื่อครู่ รออีก {0} วินาที': 'Just tried a moment ago. Wait {0} more seconds',
  'เริ่มลองรอบใหม่': 'Start a new round',
  'ลองใหม่ตอนนี้': 'Retry now',
  'ลองงาน {0} ใหม่': 'Retry job {0}',
  'เหตุผล (จะถูกบันทึกไว้ในประวัติ)': 'Reason (recorded in the history)',
  'งานนี้ลองครบ 5 ครั้งแล้ว ระบบหยุดลองเอง ปุ่มนี้เริ่มรอบใหม่อีก 5 ครั้ง (สั่งได้ 3 ครั้งต่องานใน 24 ชั่วโมง)': 'This job used all 5 attempts and the system stopped. This starts a new round of 5 attempts (3 times per job in 24 hours)',
  'ระบบลองใหม่เองหลัง 1, 5, 15 และ 60 นาทีอยู่แล้ว ปุ่มนี้แค่ไม่ต้องรอรอบถัดไป (สั่งได้ 3 ครั้งต่องานใน 24 ชั่วโมง)': 'The system already retries after 1, 5, 15 and 60 minutes; this just skips the wait (3 times per job in 24 hours)',
  'กำลังลอง…': 'Retrying…',
  'ลองใหม่': 'Retry',
  'ยกเลิก': 'Cancel',
  'บัญชีนี้ไม่มีสิทธิ์ดูงานเบื้องหลัง (ต้องเป็นโอเปอเรเตอร์หรือแอดมิน)': 'This account cannot view background jobs (operator or admin only)',
  'โหลดรายการงานไม่ได้ในขณะนี้ ลองใหม่อีกครั้ง': 'Could not load the jobs right now. Please try again',
  'ไม่มีงานที่เสร็จใน 7 วันล่าสุด': 'No jobs completed in the last 7 days',
  'งานที่ไม่สำเร็จจะถูกลองใหม่อัตโนมัติหลัง 1, 5, 15 และ 60 นาที ครบ 5 ครั้งแล้วจะหยุดรอทีมงาน · คำขอลบบัญชีต้องเสร็จใน 30 วันตาม Doc 17 ระหว่างรอบัญชียังถูกล็อก · รหัสข้อผิดพลาดเป็นรหัสสั้นเท่านั้น · รหัสงานไม่ใช่รหัสผู้ใช้':
    'Failed jobs retry automatically after 1, 5, 15 and 60 minutes, then stop after 5 attempts and wait for staff · Account deletions must finish within 30 days (Doc 17); the account stays locked meanwhile · Error codes are short codes only · Job IDs are not user IDs',
  'แสดง 100 รายการแรก': 'Showing the first 100',
  'งานเบื้องหลัง': 'Background jobs',
  'กำลังลองใหม่': 'Retrying',
  'รอทีมงาน (dead letter)': 'Waiting for staff (dead letter)',
  'เสร็จใน 7 วัน': 'Completed in 7 days',
  'คิว': 'Queue',
  'ค้างนานสุด': 'Oldest',
  'งาน': 'Job',
  'อายุ': 'Age',
  'ลองแล้ว': 'Attempts',
  'ลองล่าสุด': 'Last attempt',
  'ลองครั้งถัดไป': 'Next attempt',
  'รหัสข้อผิดพลาด': 'Error code',
  'กำหนด': 'Due',
  'สั่งงาน': 'Actions',
  'รอทำ {0} · ลองใหม่ {1} · รอทีมงาน {2} · เสร็จ 7 วัน {3}': 'Pending {0} · Retrying {1} · Waiting for staff {2} · Completed in 7 days {3}',
  'อายุ {0} · ลอง {1} · ถัดไป {2}': 'Age {0} · Attempts {1} · Next {2}',
  'คิวที่ระบบทำต่อเอง พร้อมอายุ จำนวนครั้งที่ลอง และรหัสข้อผิดพลาด · เสร็จใน 7 วัน {0}': 'Queues the system works through on its own, with age, attempts and error code · Completed in 7 days {0}',
  'อายุ {0} · ลอง {1}': 'Age {0} · Attempts {1}',
  'ถัดไป {0}': 'Next {0}',
  'รหัส {0}': 'Code {0}',
  'รายการงาน': 'Job list',
  'รายละเอียดงาน': 'Job details',
  'ขอเมื่อ': 'Requested',
  '{0} ครั้ง': '{0} attempts',
  'ระบบกำลังทำ': 'In progress',
  'ลองเองหลัง 1, 5, 15, 60 นาที': 'Retries after 1, 5, 15, 60 minutes',
  'ลองครบ 5 ครั้งแล้ว · เสร็จใน 7 วัน {0}': 'All 5 attempts used · Completed in 7 days {0}',

  // App configuration (/admin/config)
  'เลือกสถานีจากแค็ตตาล็อก': 'Browse stations from the catalog',
  'ปิดแล้วแอปยังเล่นสถานีที่บันทึกไว้ได้': 'When off, the app can still play saved stations',
  'นำเข้าเพลย์ลิสต์ M3U/EPG': 'Import M3U/EPG playlists',
  'ปิดเมื่อพบปัญหาในการนำเข้า': 'Turn off if imports have problems',
  'ส่งรายงานวินิจฉัย': 'Send diagnostic reports',
  'ส่งเฉพาะผู้ใช้ที่ยินยอม': 'Only from users who consented',
  'build ขั้นต่ำ iOS': 'Minimum iOS build',
  'build ขั้นต่ำ Android': 'Minimum Android build',
  'แค็ตตาล็อก': 'Catalog',
  'นำเข้าเพลย์ลิสต์': 'Playlist import',
  'รายงานวินิจฉัย': 'Diagnostic reports',
  'ค้นหาสถานีวิทยุทั่วโลก': 'Worldwide radio search',
  'สถานีจาก Radio Browser ที่ผู้ใช้เพิ่มเอง ปิดแล้วสถานีที่เพิ่มไว้ยังอยู่': 'Radio Browser stations that users add themselves; turning it off keeps stations already added',
  'ค้นหาวิทยุทั่วโลก': 'Worldwide radio search',
  'ดูช่องทีวีจากลิสต์ของผู้ใช้': "TV channels from the user's playlists",
  'ช่องวิดีโอจากเพลย์ลิสต์ที่ผู้ใช้นำเข้าเอง': 'Video channels from playlists users import themselves',
  'เบราว์เซอร์ในแอป': 'In-app browser',
  'เปิดเว็บอย่าง YouTube ภายในแอป': 'Opens sites such as YouTube inside the app',
  'ภาพบนจอรถ': 'Video on the car screen',
  'ทีวีและเบราว์เซอร์บน CarPlay / Android Auto ผู้ใช้ปิดเองได้ในตั้งค่าแอป ปิดตรงนี้คือปิดทุกคน': 'TV and the browser on CarPlay / Android Auto. Users can turn it off in app settings; turning it off here turns it off for everyone',
  'ช่องทีวี': 'TV channels',
  'รอบรีเฟรชแค็ตตาล็อก': 'Catalog refresh interval',
  'ส่งให้ iOS': 'Send to iOS',
  'iOS ตั้งแต่ build': 'iOS from build',
  'iOS ถึง build': 'iOS up to build',
  'ส่งให้ Android': 'Send to Android',
  'Android ตั้งแต่ build': 'Android from build',
  'Android ถึง build': 'Android up to build',
  'คุณแก้ร่างนี้เอง ต้องให้แอดมินอีกคนตรวจและเผยแพร่': 'You edited this draft, so another admin must review and publish it',
  'ร่างตรงกับที่แอปใช้อยู่แล้ว ไม่มีอะไรต้องเผยแพร่': 'The draft matches what the apps use; nothing to publish',
  'ต้องส่งร่างนี้ขึ้น staging ก่อน แล้วจึงเผยแพร่จริงได้': 'Send this draft to staging first, then it can be published',
  'ร่างนี้อยู่บน staging แล้ว': 'This draft is already on staging',
  'ย้อนกลับได้เฉพาะรุ่นที่เคยใช้จริง ไม่ใช่รุ่น staging': 'You can only roll back to a production release, not a staging one',
  '{0}: ไม่ส่ง': '{0}: not sent',
  '{0}: ทุก build': '{0}: all builds',
  'แรก': 'first',
  'ไม่บังคับ': 'Not required',
  'หมดอายุแล้ว แอปกลับไปใช้ค่าเริ่มต้น': 'Expired; the apps are back on their defaults',
  'หมดอายุใน {0} วัน ({1})': 'Expires in {0} days ({1})',
  'iOS ขั้นต่ำ': 'iOS minimum',
  'Android ขั้นต่ำ': 'Android minimum',
  'เปิด': 'On',
  'ปิด': 'Off',
  'รีเฟรชแค็ตตาล็อกทุก': 'Catalog refresh every',
  'ค่าบางช่องไม่ถูกต้อง': 'Some fields are invalid',
  'บัญชีนี้ไม่มีสิทธิ์ทำรายการนี้ (ต้องเป็นแอดมิน)': 'This account cannot do this (admin only)',
  'ไม่พบรุ่นที่เลือกแล้ว': 'The selected release no longer exists',
  'มีคนแก้ร่างก่อนคุณ โหลดหน้าใหม่เพื่อดูร่างล่าสุดแล้วลองอีกครั้ง': 'Someone changed the draft before you. Reload to see the latest draft and try again',
  'build ขั้นต่ำ iOS ต้องเป็นเลขจำนวนเต็มตั้งแต่ 1 หรือเว้นว่าง': 'Minimum iOS build must be a whole number from 1, or empty',
  'build ขั้นต่ำ Android ต้องเป็นเลขจำนวนเต็มตั้งแต่ 1 หรือเว้นว่าง': 'Minimum Android build must be a whole number from 1, or empty',
  'รอบรีเฟรชต้องอยู่ระหว่าง 1–168 ชั่วโมง': 'Refresh interval must be 1–168 hours',
  'อายุของรุ่นต้องอยู่ระหว่าง 7–90 วัน': 'Release lifetime must be 7–90 days',
  'ต้องส่งให้อย่างน้อยหนึ่งแพลตฟอร์ม': 'Send to at least one platform',
  'build เริ่มต้นของ {0} ต้องเป็นเลขจำนวนเต็มตั้งแต่ 1 หรือเว้นว่าง': '{0} first build must be a whole number from 1, or empty',
  'build สุดท้ายของ {0} ต้องเป็นเลขตั้งแต่ 1 และไม่น้อยกว่า build เริ่มต้น หรือเว้นว่าง': '{0} last build must be a number from 1 and not below the first build, or empty',
  'รุ่นนี้คือรุ่นที่ใช้อยู่แล้ว': 'This release is already in use',
  'ยังเผยแพร่ไม่ได้': 'Cannot publish yet',
  'บันทึกไม่ได้ในขณะนี้ ลองใหม่อีกครั้ง': 'Could not save right now. Please try again',
  'บันทึกร่างแล้ว แอปยังไม่เห็นจนกว่าจะส่งขึ้น staging และแอดมินอีกคนเผยแพร่': 'Draft saved. Apps will not see it until it goes to staging and another admin publishes it',
  'ร่างตั้งค่าแอป': 'App config draft',
  'รีเฟรชแค็ตตาล็อกทุก (ชั่วโมง)': 'Catalog refresh every (hours)',
  'แอปที่ build ต่ำกว่านี้จะขอให้อัปเดตก่อนใช้งานออนไลน์ เว้นว่างได้': 'Apps below this build will ask to update before going online. Can be left empty',
  'ฟีเจอร์': 'Features',
  'ปิดได้เฉพาะฟีเจอร์ที่มีอยู่ในแอปแล้ว ใช้เปิดฟีเจอร์ใหม่ที่แอปไม่มีไม่ได้': 'Only turns off features the app already has; it cannot turn on new ones',
  'ส่งให้แอปไหน': 'Which apps receive it',
  'ส่งให้ {0}': 'Send to {0}',
  '{0} ตั้งแต่ build': '{0} from build',
  'ทุก build': 'All builds',
  '{0} ถึง build': '{0} up to build',
  'แอปที่อยู่นอกช่วงนี้จะไม่สนใจรุ่นนี้ และใช้รุ่นล่าสุดที่ตรงกับตัวเองต่อไป': 'Apps outside this range ignore this release and keep the latest one that matches them',
  'กำลังบันทึก…': 'Saving…',
  'บันทึกร่าง': 'Save draft',
  'ดูได้อย่างเดียว เฉพาะแอดมินแก้ไขได้': 'View only. Only admins can edit',
  'ร่าง r{0} ต่างจากที่ใช้อยู่:': 'Draft r{0} differs from what is in use:',
  'ร่าง r{0} ตรงกับที่แอปใช้อยู่': 'Draft r{0} matches what the apps use',
  'Staging: รุ่น {0} จากร่าง r{1} (ตรงกับร่างนี้)': 'Staging: release {0} from draft r{1} (matches this draft)',
  'Staging: รุ่น {0} จากร่าง r{1} (เก่ากว่าร่างนี้)': 'Staging: release {0} from draft r{1} (older than this draft)',
  'Staging: ยังไม่มีรุ่นทดสอบ': 'Staging: no test release yet',
  'ส่งขึ้น staging': 'Send to staging',
  'ส่งขึ้น staging แล้ว แอปรุ่นทดสอบจะได้รับเมื่อเชื่อมต่อครั้งถัดไป': 'Sent to staging. Test builds get it the next time they connect',
  '1. ส่งร่าง r{0} ขึ้น staging ให้แอปรุ่นทดสอบลองก่อน (เหตุผล)': '1. Send draft r{0} to staging for test builds first (reason)',
  'กำลังส่ง…': 'Sending…',
  'ส่งร่าง r{0} ขึ้น staging': 'Send draft r{0} to staging',
  'กรณีฉุกเฉิน: เผยแพร่โดยไม่มีแอดมินคนที่สอง': 'Emergency: publish without a second admin',
  'เผยแพร่ฉุกเฉิน': 'Emergency publish',
  'เผยแพร่แบบฉุกเฉินแล้ว บันทึกใน audit ให้ทีมตรวจย้อนหลัง': 'Published as an emergency. Logged in the audit for later review',
  'ใช้เมื่อรอแอดมินคนอื่นไม่ได้ ต้องยืนยัน MFA ภายใน 5 นาที และบันทึกใน audit แยกเป็น “เผยแพร่แบบฉุกเฉิน”': 'Use only when you cannot wait for another admin. Requires MFA within 5 minutes and is logged in the audit as “emergency publish”',
  'เหตุผลที่ต้องเผยแพร่ทันที (อย่างน้อย 20 ตัวอักษร)': 'Why this must be published now (at least 20 characters)',
  'ฉันตรวจร่างนี้แล้ว และเข้าใจว่าไม่มีผู้ตรวจคนที่สอง': 'I reviewed this draft and understand there is no second reviewer',
  'เผยแพร่ฉุกเฉิน r{0}': 'Emergency publish r{0}',
  'เผยแพร่ร่าง': 'Publish draft',
  'เผยแพร่แล้ว แอปจะได้รับเมื่อเปิดแอปหรือเชื่อมต่อครั้งถัดไป': 'Published. Apps get it when they next open or connect',
  '2. เผยแพร่ให้ทุกคน · เหตุผล (จะถูกบันทึกไว้ในประวัติ)': '2. Publish to everyone · Reason (recorded in the history)',
  'กำลังเผยแพร่…': 'Publishing…',
  'เผยแพร่ร่าง r{0}': 'Publish draft r{0}',
  'ใช้ได้นาน': 'Valid for',
  'ย้อนกลับไปใช้ค่าของรุ่น {0} แล้ว (เป็นรุ่นใหม่ในประวัติ)': 'Rolled back to the settings of release {0} (as a new release in the history)',
  'ย้อนไปใช้รุ่น {0}': 'Roll back to release {0}',
  'ร่างไม่เปลี่ยน ระบบจะออกรุ่นใหม่ที่ใช้ค่าเดียวกับรุ่น {0}': 'The draft stays the same; a new release is issued with the settings of release {0}',
  'กำลังย้อน…': 'Rolling back…',
  'ย้อนกลับ': 'Roll back',
  'ย้อนจากรุ่น {0}': 'rolled back from release {0}',
  'จากร่าง r{0}': 'from draft r{0}',
  'ผ่าน staging รุ่น {0}': 'via staging release {0}',
  'เผยแพร่ฉุกเฉิน ไม่มีผู้ตรวจ': 'emergency publish, no reviewer',
  'ผ่านผู้ตรวจ': 'reviewed',
  'คุณเผยแพร่': 'published by you',
  'ยังไม่เคยเผยแพร่ แอปใช้ค่าเริ่มต้นของแอปเอง': 'Never published; the apps use their own defaults',
  'รุ่น {0}': 'Release {0}',
  'ใช้อยู่': 'In use',
  'แอปใช้': 'Apps use',
  'แอปรับค่าใหม่ตอนเปิดแอปหรือเชื่อมต่อใหม่ ไม่ใช่ทันที · ทุกรุ่นมีลายเซ็นจากเซิร์ฟเวอร์ (กุญแจ {0}) แอปจะเชื่อเฉพาะค่าที่ลายเซ็นถูกต้อง · รุ่นที่หมดอายุแล้ว แอปจะกลับไปใช้ค่าเริ่มต้น':
    'Apps pick up new settings when they open or reconnect, not instantly · Every release is signed by the server (key {0}) and apps trust only validly signed settings · When a release expires, apps go back to their defaults',
  'บัญชีนี้ไม่มีสิทธิ์ดูตั้งค่าแอป (ต้องเป็นโอเปอเรเตอร์หรือแอดมิน)': 'This account cannot view app config (operator or admin only)',
  'โหลดตั้งค่าแอปไม่ได้ในขณะนี้ ลองใหม่อีกครั้ง': 'Could not load app config right now. Please try again',
  'ตั้งค่าแอป': 'App config',
  'รุ่นที่ใช้': 'Release in use',
  'หมดอายุใน': 'Expires in',
  'รอเผยแพร่': 'Awaiting publish',
  '{0} ค่า': '{0} settings',
  'ร่าง r{0}': 'Draft r{0}',
  'เผยแพร่': 'Publish',
  'ที่แอปใช้อยู่': 'In use by the apps',
  'ประวัติรุ่น': 'Release history',
  'ON AIR รุ่น {0} · {1}': 'ON AIR release {0} · {1}',
  'ยังไม่ออกอากาศ ใช้ค่าเริ่มต้น': 'Not on air yet, using defaults',
  'ออกอากาศ': 'On air',
  'เวอร์ชันขั้นต่ำ ฟีเจอร์ที่ปิดชั่วคราว และรอบรีเฟรช ที่แอปจะได้รับ': 'Minimum versions, temporarily disabled features and refresh interval the apps receive',
  'รุ่นที่แอปใช้': 'Release the apps use',
  'ร่างและการเผยแพร่': 'Draft and publishing',
  'แอปใช้รุ่น {0}': 'Apps use release {0}',
  'ยังไม่เคยเผยแพร่': 'Never published',
  'ใช้ค่าเริ่มต้นของแอป': 'Using the app defaults',
  'เผยแพร่ใหม่ก่อนหมดอายุ': 'Publish again before it expires',
  'ร่างตรงกับที่ใช้อยู่': 'The draft matches what is in use',
  'แก้ล่าสุด {0}': 'Last edited {0}',
  'ยังไม่เคยแก้': 'Never edited',
  'ต้องให้แอดมินอีกคนตรวจ': 'Needs another admin to review',
  'ย้อนกลับได้โดยออกรุ่นใหม่ ไม่แก้ประวัติ': 'Rolling back issues a new release; history is never edited',
};
