/** English for the staff console (people), keyed by the Thai text. `{0}`, `{1}` … are filled in by t(). */
export const EN_PEOPLE: Record<string, string> = {
  // Shared by users, audit and logs
  'ค้นหา': 'Search',
  'ล้างตัวกรอง': 'Clear filters',
  'ช่วงเวลา': 'Time range',
  'ตัวกรอง': 'filter',
  'ค่าที่กรอกไม่ถูกต้อง: {0}': 'Invalid value: {0}',
  'เวลา': 'Time',
  'เวลา (ไทย)': 'Time (Thailand)',
  'เหตุการณ์': 'Event',
  'ใช้เวลา': 'Duration',
  'ผู้ใช้': 'Users',
  'รายละเอียด': 'Details',
  'ผลการค้นหา': 'Search results',
  'เลื่อน': 'move',
  'หน้าแรก': 'First page',
  '← กลับหน้าแรก': '← Back to first page',
  'เก่ากว่า →': 'Older →',
  'ล่าสุด': 'Latest',
  '↻ ล่าสุด': '↻ Latest',
  'โหลดล่าสุด': 'Load latest',

  // Users (support lookup)
  'ใช้งานอยู่': 'Active',
  'กำลังลบบัญชี': 'Deleting account',
  'ลบบัญชีแล้ว': 'Account deleted',
  'ระงับการใช้งาน': 'Disabled',
  'กำลังลบ': 'Deleting',
  'ลบไม่สำเร็จ กำลังลองใหม่': 'Deletion failed, retrying',
  'ลบไม่สำเร็จ ลองครบ 5 ครั้ง รอทีมงานสั่งลองใหม่ (บัญชียังถูกล็อก)': 'Deletion failed after 5 tries; waiting for staff to retry (account stays locked)',
  'ลบเสร็จแล้ว': 'Deleted',
  'ออกจากระบบแล้ว': 'Signed out',
  'ได้รับการตั้งค่าล่าสุดแล้ว': 'Has the latest settings',
  'ยังไม่ได้รับการตั้งค่าล่าสุด (ใช้ r{0} จาก r{1})': 'Missing the latest settings (on r{0} of r{1})',
  'ใส่อีเมล หรือรหัสผู้ใช้/รหัสเครื่องให้ครบ (รูปแบบ xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx)': 'Enter an email, or a full user/device ID (format xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx)',
  'กรอกเหตุผล 10–500 ตัวอักษร': 'Enter a reason of 10–500 characters',
  'ไม่พบบัญชีที่ตรงกัน (หรืออีเมลนี้มีมากกว่าหนึ่งบัญชี ให้ค้นด้วยรหัสแทน) การค้นครั้งนี้ถูกบันทึกแล้ว': 'No matching account (or this email has more than one account; search by ID instead). This search was recorded.',
  'บัญชีนี้ไม่มีสิทธิ์ดูข้อมูลผู้ใช้ (ต้องเป็นซัพพอร์ตหรือแอดมิน)': 'This account can’t view user data (support or admin role required)',
  'หมดเวลาใช้งาน เข้าสู่ระบบใหม่แล้วลองอีกครั้ง': 'Your session expired. Sign in again and retry.',
  'ค้นหาไม่ได้ในขณะนี้ ลองใหม่อีกครั้ง': 'Search is unavailable right now. Try again.',
  'ค้นหาผู้ใช้': 'Find a user',
  'อีเมล รหัสผู้ใช้ หรือรหัสเครื่อง': 'Email, user ID or device ID',
  'name@example.com หรือ xxxxxxxx-xxxx-…': 'name@example.com or xxxxxxxx-xxxx-…',
  'เหตุผล (จะถูกบันทึกไว้ในประวัติ)': 'Reason (recorded in the audit trail)',
  'เช่น ลูกค้าแจ้งว่าตั้งค่าไม่ซิงก์ เคส #1042': 'e.g. customer says settings don’t sync, case #1042',
  'กำลังค้น…': 'Searching…',
  'ข้อมูลเท่าที่ซัพพอร์ตต้องใช้ ไม่มีค่าที่ตั้งหรือสถานีของผู้ใช้ · ทุกการค้นถูกบันทึกในประวัติพร้อมเหตุผล (ไม่บันทึกอีเมลที่ค้น)': 'Only what support needs: no setting values or stations · Every lookup is recorded with its reason (the email searched is not stored)',
  'ใส่อีเมล รหัสผู้ใช้ หรือรหัสเครื่องที่ลูกค้าแจ้ง พร้อมเหตุผล แล้วกดค้นหา': 'Enter the email, user ID or device ID the customer gave you, add a reason, then search',
  'อีเมล': 'Email',
  '{0} (ยังไม่ยืนยัน)': '{0} (not verified)',
  'ไม่มี': 'None',
  'รหัสผู้ใช้': 'User ID',
  'สมัครเมื่อ': 'Signed up',
  'การตั้งค่า': 'Settings',
  'r{0} · บันทึก {1}': 'r{0} · saved {1}',
  'ยังไม่เคยบันทึก': 'Never saved',
  'รายงานวินิจฉัย 7 วัน': 'Diagnostics, 7 days',
  '{0} ฉบับ': '{0} reports',
  'การลบบัญชี': 'Account deletion',
  '{0} · ขอเมื่อ {1}': '{0} · requested {1}',
  'ไม่มีคำขอ': 'No request',
  'ยังไม่มีเครื่องลงทะเบียน': 'No registered devices yet',
  'เครื่องของผู้ใช้': 'User’s devices',
  'เครื่อง': 'Device',
  'แอป': 'App',
  'ติดต่อล่าสุด': 'Last seen',
  'สถานะ': 'Status',
  'รหัสต้องมี 8 ตัว เช่น ABCD-EFGH': 'The code has 8 characters, e.g. ABCD-EFGH',
  'รหัสนี้ใช้ไม่ได้ (ผิด ใช้ไปแล้ว หมดอายุ หรือเป็นของบัญชีอื่น) ให้ลูกค้าสร้างรหัสใหม่ การลองครั้งนี้ถูกบันทึกแล้ว': 'This code doesn’t work (wrong, already used, expired or for another account). Ask the customer for a new one. This attempt was recorded.',
  'สิทธิ์ดูรายงานหมดแล้ว หรือลูกค้ายกเลิกแล้ว ขอรหัสใหม่จากลูกค้า': 'Access to the reports has ended or the customer withdrew it. Ask the customer for a new code.',
  'ทำรายการไม่ได้ในขณะนี้ ลองใหม่อีกครั้ง': 'Can’t do that right now. Try again.',
  'ขอดูรายงานวินิจฉัย': 'Request diagnostics access',
  'ให้ลูกค้ากด “สร้างรหัสให้ทีม support” ในหน้าความเป็นส่วนตัว แล้วอ่านรหัสให้ฟัง รหัสใช้ได้ครั้งเดียวภายใน 1 ชั่วโมง': 'Ask the customer to tap “Create a code for support” on the privacy page and read it to you. The code works once, within 1 hour.',
  'รหัสจากลูกค้า': 'Code from the customer',
  'เหตุผลที่ขอดูรายงาน (จะถูกบันทึกไว้ในประวัติ)': 'Reason for viewing the reports (recorded in the audit trail)',
  'เช่น ลูกค้าแจ้งว่าเล่นวิทยุไม่ได้ เคส #1042': 'e.g. customer says radio won’t play, case #1042',
  'กำลังตรวจรหัส…': 'Checking code…',
  'ขอดูรายงาน': 'Request access',
  'ลูกค้าให้สิทธิ์คุณดูรายงานได้ถึง {0} · การเปิดดูถูกบันทึก': 'The customer let you view reports until {0} · Viewing is recorded',
  'กำลังโหลด…': 'Loading…',
  'เปิดดูรายงาน': 'Open reports',
  'ดูได้ถึง {0} · รายงานถูกลบเองเมื่อครบ {1} วัน · มีแค่รหัสผลลัพธ์ ไม่มีชื่อช่อง ลิงก์ หรือตำแหน่ง': 'Viewable until {0} · Reports are deleted after {1} days · Result codes only, no station names, links or location',
  'ไม่มีรายงานใน {0} วันที่ผ่านมา': 'No reports in the last {0} days',
  'เครื่องที่ออกจากระบบแล้ว': 'Signed-out device',
  '{0} เหตุการณ์': '{0} events',
  'เวลา (วินาที)': 'Time (s)',
  'ผลลัพธ์': 'Result',
  'เครือข่าย': 'Network',
  'พบจากรหัสเครื่อง': 'Found by device ID',
  'พบจากอีเมล': 'Found by email',
  'พบจากรหัสผู้ใช้': 'Found by user ID',
  'บัญชี': 'Account',
  'เครื่องที่ใช้อยู่': 'Active devices',
  'ทั้งหมด {0}': '{0} total',
  'ยังไม่ได้รับการตั้งค่าล่าสุด': 'Missing latest settings',
  'การตั้งค่า r{0}': 'Settings r{0}',
  'ผู้ใช้ · Support Desk': 'Users · Support Desk',
  'ค้นได้ทีละบัญชี พร้อมเหตุผล': 'One account at a time, with a reason',
  'บัญชี: {0} · {1}': 'Account: {0} · {1}',
  'เครื่องที่ยังไม่ได้รับการตั้งค่าล่าสุด {0} จาก {1}': 'Devices missing the latest settings: {0} of {1}',
  'ล่าสุด {0}': 'Last seen {0}',
  'รายงานวินิจฉัย': 'Diagnostics',
  'ช่วยลูกค้าจากรหัสที่เขาแจ้ง ดูได้ทีละบัญชี': 'Help a customer from the ID they give you, one account at a time',
  'จาก {0} เครื่องที่ใช้อยู่': 'of {0} active devices',
  'แอป {0} · ล่าสุด {1}': 'App {0} · last seen {1}',
  'ดูได้ถึง {0}': 'Viewable until {0}',
  '{0} ฉบับ · ต้องมีรหัสจากลูกค้า': '{0} reports · needs a code from the customer',
  'ผลการค้น': 'Results',
  'ผู้ใช้ / รายงานวินิจฉัย': 'Users / Diagnostics',
  'ผู้ใช้ / เครื่อง': 'Users / Device',
  'รหัสเครื่อง': 'Device ID',
  'ลงทะเบียน': 'Registered',
  'ผู้ใช้ / บัญชี · {0}': 'Users / Account · {0}',
  'ใช้อีเมลหรือรหัสที่ลูกค้าแจ้ง ดูได้ทีละบัญชี': 'Use the email or ID the customer gives you, one account at a time',
  'ทั้งหมด {0} เครื่อง': '{0} devices total',
  'ใน 7 วัน': 'in 7 days',
  'เรียงจากที่ติดต่อล่าสุด': 'Most recently seen first',
  'ดูได้เมื่อลูกค้าให้รหัส': 'Available when the customer gives you a code',

  // Audit trail
  'บันทึกนี้แก้ไขหรือลบไม่ได้ และการเปิดดูแต่ละครั้งก็ถูกบันทึกไว้': 'This record can’t be edited or deleted, and every view is recorded too',
  'สถานี': 'Station',
  'ดูทุกอย่างที่ {0} ทำ': 'See everything {0} did',
  'บัญชีนี้ไม่มีสิทธิ์ดูประวัติการแก้ไข (ต้องเป็นผู้ตรวจสอบหรือแอดมิน)': 'This account can’t view the audit trail (auditor or admin role required)',
  'โหลดประวัติไม่ได้ในขณะนี้ ลองใหม่อีกครั้ง': 'Can’t load the audit trail right now. Try again.',
  'ไม่พบรายการตามเงื่อนไขนี้ในช่วงเวลาที่เลือก': 'No entries match these filters in the selected time range',
  'ค้นหาประวัติ': 'Search audit trail',
  'การกระทำ': 'Action',
  'ผู้กระทำ': 'Actor',
  'subject หรือ operator:ชื่อ': 'subject or operator:name',
  'เป้าหมาย (id)': 'Target (id)',
  'รวมการเปิดดู': 'Include views',
  'ส่งออกได้เฉพาะ auditor หรือ admin': 'Only auditors or admins can export',
  'ส่งออกประวัติ': 'Export audit trail',
  'รายการ': 'entries',
  'หน้าประวัติ': 'Audit pages',
  'แสดง {0} รายการ ใหม่สุดก่อน': 'Showing {0} entries, newest first',
  'เป้าหมาย': 'Target',
  'เหตุผล': 'Reason',
  'สิ่งที่เปลี่ยน': 'Changes',
  'รายการประวัติ': 'Audit entries',
  'ประวัติการแก้ไข': 'Audit trail',
  'ประวัติการแก้ไข /': 'Audit trail /',
  'เลือกรายการจากทางซ้าย': 'Pick an entry on the left',
  'ประวัติการแก้ไข ใหม่สุดก่อน': 'Audit trail, newest first',
  'ประวัติการแก้ไข · Logbook': 'Audit trail · Logbook',
  'โดย': 'by',
  'สรุปรายการในหน้านี้': 'Summary of entries on this page',
  'รายการในหน้านี้': 'Entries on this page',
  'เกี่ยวกับสถานี': 'Station changes',
  'เปลี่ยนสิทธิ์ทีมงาน': 'Staff role changes',
  'คนที่เกี่ยวข้อง': 'People involved',
  'สร้าง แก้ เผยแพร่ ปิด': 'Create, edit, publish, disable',
  'ให้หรือถอนบทบาท': 'Roles granted or revoked',
  'บัญชีและโอเปอเรเตอร์': 'Accounts and operators',

  // System logs
  'บัญชีนี้ไม่มีสิทธิ์ดูบันทึกระบบ (ต้องเป็นโอเปอเรเตอร์หรือแอดมิน)': 'This account can’t view system logs (operator or admin role required)',
  'โหลดบันทึกไม่ได้ในขณะนี้ ลองใหม่อีกครั้ง': 'Can’t load logs right now. Try again.',
  'ไม่พบบันทึกตามเงื่อนไขนี้ในช่วงเวลาที่เลือก': 'No log lines match these filters in the selected time range',
  'ค้นหาบันทึก': 'Search logs',
  'ระดับ': 'Level',
  'req_… หรือ web_…': 'req_… or web_…',
  'เช่น 500': 'e.g. 500',
  'รหัสข้อผิดพลาด': 'Error code',
  '32 ตัวอักษร 0-9 a-f': '32 characters 0-9 a-f',
  'รหัสเหตุการณ์': 'Event code',
  'ส่งออกได้เฉพาะโอเปอเรเตอร์หรือแอดมิน': 'Only operators or admins can export',
  'ส่งออกบันทึกระบบ': 'Export system logs',
  'บรรทัด': 'lines',
  'หน้าบันทึก': 'Log pages',
  'แสดง {0} บรรทัด ใหม่สุดก่อน': 'Showing {0} lines, newest first',
  'บันทึกระบบ ใหม่สุดก่อน': 'System logs, newest first',
  'คำขอ': 'Request',
  'ดูทุกบรรทัดของ {0}': 'See every line of {0}',
  'ดูทุกบรรทัดของ trace {0}': 'See every line of trace {0}',
  'ตัดข้อมูลลับออกแล้ว เก็บ 14 วัน ค้นได้ทีละไม่เกิน 24 ชั่วโมง ทุกการค้นหาและการส่งออกถูกบันทึกใน audit': 'Secrets removed. Kept 14 days; search up to 24 hours at a time. Every search and export is recorded in the audit trail.',
  'ผู้ใช้ (id ภายใน)': 'User (internal id)',
  'รายการบันทึก': 'Log lines',
  'บันทึกระบบ': 'System logs',
  'รายละเอียดบรรทัด': 'Line details',
  'บันทึกระบบ /': 'System logs /',
  'ดูทุกบรรทัดของคำขอนี้': 'See every line of this request',
  'ดูทั้ง trace (เว็บและ API)': 'See the whole trace (web and API)',
  'เลือกบรรทัดจากรายการทางซ้าย': 'Pick a line from the list on the left',
  'บันทึกระบบ · Monitor': 'System logs · Monitor',
  'สรุปบรรทัดในหน้านี้': 'Summary of lines on this page',
  'บรรทัดในหน้านี้': 'Lines on this page',
  'เวลาเฉลี่ย': 'Average time',
  '4xx และคำเตือน': '4xx and warnings',
  '5xx และข้อผิดพลาด': '5xx and errors',
  'เวลาตอบเฉลี่ย': 'Average response time',
  'เฉพาะคำขอ HTTP': 'HTTP requests only',
};
