/** English for the staff console (stations), keyed by the Thai text. `{0}`, `{1}` … are filled in by t(). */
export const EN_STATIONS: Record<string, string> = {
  'แผงหน้าปัดรถ': 'Cockpit',
  'แผงสถานีและข้อมูลคอลเลกชัน พรีเซ็ตหกช่องในเบราว์เซอร์ โทนเข้ม': 'A station dashboard and collection counts; six browser presets, dark appearance',
  'หน้าปัดวิทยุรถ': 'Head unit',
  'เลือกสถานีด้วยแถบตำแหน่ง กดเล่นแยกต่างหาก พรีเซ็ตในเบราว์เซอร์ โทนเข้ม': 'A station-position strip with separate Play controls; browser presets, dark appearance',

  'ค้นหาซ้าย ฟังขวา': 'Listen and find',
  'ค้นหาสถานีด้านซ้าย แผงฟังด้านขวาอยู่ที่เดิมทุกหน้า': 'Search on the left; a listening panel stays on the right on every page',
  'หน้าต่างประเทศ': 'Country window',
  'เลือกประเทศเอง รายการสถานีและพรีเซ็ตหกช่อง พร้อมแผงฟังด้านขวา': 'Choose a country; stations and six presets with a listening panel on the right',
  'เวที': 'Stage',
  'เวทีสถานีขนาดใหญ่บนหน้าแรก และแถบเล่นต่อเนื่องในหน้าอื่น': 'A large station stage on Home; a continuous player bar on other pages',

  'โลโก้ของ {0}': 'Logo of {0}',
  'เลือกรูปโลโก้ของ {0}': 'Choose a logo picture for {0}',
  'ลบโลโก้ที่อัปโหลด': 'Remove the uploaded logo',
  'บัญชีนี้ไม่มีสิทธิ์เปลี่ยนโลโก้นี้': 'This account may not change this logo',
  'ใช้รูป PNG, JPEG หรือ WebP ที่ไม่ใหญ่เกินไป': 'Use a PNG, JPEG or WebP picture that is not too large',
  'โลโก้ที่ทีมงานอัปโหลด': 'Logo uploaded by staff',
  'โลโก้จาก Radio Browser (ถ้าโหลดไม่ได้ใช้โลโก้ TuneDeck)': 'Logo from Radio Browser (TuneDeck logo if it cannot load)',
  'ไม่มีโลโก้ ใช้โลโก้ TuneDeck': 'No logo, the TuneDeck logo shows',
  'เปลี่ยนโลโก้': 'Change logo',
  'อัปโหลดโลโก้': 'Upload logo',
  'พิมพ์ละติจูด, ลองจิจูด เช่น 13.7563, 100.5018': 'Type latitude, longitude, e.g. 13.7563, 100.5018',
  '📍 {0} (ทีมงานใส่)': '📍 {0} (set by staff)',
  '📍 {0} (จาก Radio Browser)': '📍 {0} (from Radio Browser)',
  'ไม่มีพิกัด ไม่ขึ้นบนแผนที่': 'No place, not on the map',
  'แก้พิกัด': 'Edit place',
  'ใส่พิกัด': 'Set place',
  'พิกัดของ {0}': 'Place of {0}',
  'ละติจูด, ลองจิจูด (คัดลอกจาก Google Maps ได้)': 'Latitude, longitude (you can copy it from Google Maps)',
  'ดูตำแหน่งนี้ใน Google Maps': 'See this place in Google Maps',
  'บันทึกพิกัด': 'Save place',
  'ลบพิกัดที่ใส่เอง': 'Remove the place set by hand',
  'ทุกประเทศ (ค้นด้วยชื่อ)': 'All countries (search by name)',
  'ประเทศหลัก': 'Main countries',
  'ยุโรป': 'Europe',
  'ประเทศอื่น': 'Other countries',
  'ทุกสถานะ': 'Any status',
  'เปิดอยู่': 'Enabled',
  'เปิดสถานี': 'Enable station',
  'ปิดทั้งโฮสต์ {0} · เปิดได้จากรายการที่บล็อก': 'Whole host {0} is disabled · enable it from the block list',
  'เลือกประเทศหรือค้นหาชื่อสถานี แล้วเปิดหรือปิดแต่ละสถานีได้ สถานีที่ปิดจะไม่ขึ้นในการค้นหาและบนแผนที่ของผู้ใช้': "Pick a country or search a name, then enable or disable each station. Disabled stations don't appear in users' search or on the map",
  'ไม่พบสถานี': 'No stations found',
  'พบ {0} สถานี · แสดง {1}–{2}': '{0} stations · showing {1}–{2}',
  '(อ่านได้ถึง 5000 สถานีแรก)': '(first 5000 stations only)',
  '← ก่อนหน้า': '← Previous',
  'ถัดไป →': 'Next →',
  'วิทยุทั่วโลก': 'Worldwide radio',
  'รหัสสถานีต้องเป็น UUID ของ Radio Browser หรือโดเมนต้องเป็นชื่อโฮสต์ เช่น stream.example.com': 'A station id must be a Radio Browser UUID, and a host must be a host name such as stream.example.com',
  'รายการนี้ถูกบล็อกไว้แล้ว': 'This is already blocked',
  'บัญชีนี้ไม่มีสิทธิ์ (ต้องเป็นผู้ดูแลแค็ตตาล็อกหรือแอดมิน)': "This account can't do this (needs catalog editor or admin)",
  'ไม่พบรายการนี้แล้ว': 'This entry no longer exists',
  'ซ่อนสถานี “{0}” จากผลค้นหา': 'Hide “{0}” from search results',
  'ซ่อนทุกสถานีบนโฮสต์ {0} และโดเมนย่อย': 'Hide every station on {0} and its subdomains',
  'ประเภท': 'Type',
  'โฮสต์ของสตรีม': 'Stream host',
  'รหัสสถานี Radio Browser': 'Radio Browser station id',
  'โฮสต์ เช่น stream.example.com': 'Host, e.g. stream.example.com',
  'รหัสสถานี (UUID)': 'Station id (UUID)',
  'ผู้ใช้ที่เพิ่มสถานีนี้ไว้แล้วยังเก็บไว้ในรายการของตัวเองได้ เราไม่ลบรายการของผู้ใช้': "Users who already added it keep it in their own list; we don't delete user lists",
  'บล็อก': 'Block',
  'ยกเลิกบล็อก': 'Lift block',
  'ยกเลิกบล็อก {0}': 'Lift block on {0}',
  'ค้นหาชื่อสถานีแบบที่ผู้ใช้เห็น': 'Search station names as users see them',
  'บล็อกสถานีนี้': 'Block this station',
  'บล็อกทั้งโฮสต์': 'Block the whole host',
  'ค้นหาชื่อสถานีเพื่อดูผลแบบเดียวกับที่ผู้ใช้เห็นในแอป แล้วบล็อกสถานีหรือโฮสต์ที่มีปัญหาได้จากรายการ': 'Search a station name to see the same results users see in the app, then block a station or host from the list',
  'การค้นหาวิทยุทั่วโลกยังไม่เปิด (ตั้ง RADIO_BROWSER_BASE_URL) หรือ Radio Browser ไม่ตอบในขณะนี้': "Worldwide radio search is off (set RADIO_BROWSER_BASE_URL) or Radio Browser isn't answering right now",
  'ค้นหาไม่ได้ในขณะนี้': "Search isn't available right now",
  'ข้อมูลสถานีมาจาก {0} ไม่ใช่แค็ตตาล็อกที่เราคัดเอง ผู้ใช้เป็นคนเลือกเพิ่มเอง · ระบบกรองเฉพาะสตรีม https ที่เล่นได้ · บล็อกมีผลกับการค้นหาครั้งถัดไปทันที': 'Station data comes from {0}, not our curated catalog; users choose what to add · only playable https streams are shown · a block applies from the next search',
  'โฮสต์': 'Host',
  '{0} · โดย {1} · {2}': '{0} · by {1} · {2}',
  'บล็อกอยู่ {0} รายการ': '{0} blocked',
  '+ บล็อกด้วยรหัสหรือโฮสต์': '+ Block by id or host',
  'ยังไม่มีรายการที่บล็อก': 'Nothing blocked yet',
  'ค่า': 'Value',
  'เมื่อ': 'When',
  'รายการที่บล็อก': 'Blocked',
  'สถานีจากชุมชน Radio Browser ที่ผู้ใช้ค้นแล้วเพิ่มเอง · บล็อกอยู่ {0} รายการ': 'Community stations from Radio Browser that users find and add themselves · {0} blocked',
  'บล็อก{0}': 'Blocked {0}',
  'สถานีจากชุมชน Radio Browser ที่ผู้ใช้ค้นแล้วเพิ่มเอง': 'Community stations from Radio Browser that users find and add themselves',
  'ผลค้นหาแบบที่ผู้ใช้เห็น': 'Results as users see them',
  'เปิดดู': 'open',
  'ผลค้นหา “{0}” จากทั้งแคตตาล็อก {1} สถานี': 'Search “{0}” across the whole catalog: {1} stations',
  'แคตตาล็อกยาวเกินกว่าจะแสดงทั้งหมด หน้านี้แสดง {0} สถานีแรกตามชื่อ ค้นหาชื่อเพื่อดูสถานีอื่น': 'The catalog is too long to show at once. This page shows the first {0} stations by name; search by name to find the others.',
  'ล้างการค้นหา': 'Clear search',
  'บัญชีนี้ไม่มีสิทธิ์ดูรายการสถานี': "This account can't view the station list",
  'ไม่พบสถานีนี้': 'Station not found',
  'โหลดข้อมูลไม่ได้ในขณะนี้ ลองโหลดหน้าใหม่': "Couldn't load the data right now. Try reloading the page.",
  'ประวัติเวอร์ชัน': 'Version history',
  'โหลดประวัติไม่ได้ ลองโหลดหน้าใหม่': "Couldn't load the history. Try reloading the page.",
  'ยังไม่มีประวัติ': 'No history yet',
  'กำลังโหลด…': 'Loading…',
  'โหลดเพิ่ม': 'Load more',
  'บัญชีนี้ดูได้อย่างเดียว': 'This account is view-only',
  'สร้างไม่สำเร็จ ลองอีกครั้ง': "Couldn't create it. Try again.",
  'เชื่อมต่อระบบไม่ได้ ลองอีกครั้ง': "Couldn't reach the system. Try again.",
  'เช่น Bangkok Jazz 24': 'e.g. Bangkok Jazz 24',
  'กำลังสร้าง…': 'Creating…',
  'สร้างร่างแล้วกรอกต่อ': 'Create draft and continue',
  'ประเทศและภาษาเริ่มที่ TH / ไทย แก้ได้ในหน้าถัดไป': 'Country and language start as TH / Thai; change them on the next page.',
  'รอตรวจล่าสุด': 'Latest awaiting review',
  'ดูทั้งหมด': 'View all',
  'ไม่มีงานรอตรวจ': 'Nothing awaiting review',
  'เผยแพร่ r{0}': 'Published r{0}',
  'ยังไม่เคยเผยแพร่': 'Never published',
  'สิทธิ์ใกล้หมดอายุ': 'Rights expiring soon',
  'ภายใน {0} วัน หลังหมดอายุแอปจะไม่เห็นสถานีเอง': 'Within {0} days. After expiry the apps stop showing the station automatically.',
  '{0} รายการ': '{0} items',
  'ไม่มีสิทธิ์ที่ใกล้หมดอายุ': 'No rights expiring soon',
  'ไม่มีเลขอ้างอิง': 'No reference',
  'หมดแล้ว': 'Expired',
  'เหลือ {0} วัน': '{0} days left',
  '+ เพิ่มสถานี': '+ Add station',
  'สตรีมที่ต้องดู': 'Streams to look at',
  'ผลตรวจสตรีมของสถานีที่แอปเห็น ระบบไม่ปิดสถานีเอง': 'Stream checks for stations the apps see. Stations are never disabled automatically.',
  'สรุปผลตรวจ': 'Check summary',
  'ทุกสถานีที่ตรวจแล้วเล่นได้': 'Every checked station plays',
  'ยังไม่มีผลตรวจ': 'No check results yet',
  'สถานีที่แอปเห็นตอนนี้': 'Stations the apps see now',
  'แค็ตตาล็อกสาธารณะสำหรับแอป': 'Public catalog for the apps',
  'สถานีทั้งหมดในระบบ': 'All stations in the system',
  'เผยแพร่ล่าสุด': 'Last published',
  'ยังไม่มี': 'None yet',
  'ดูสถานีที่เผยแพร่': 'View published stations',
  'ดูสถานีที่ปิดอยู่': 'View disabled stations',
  'งานรอตรวจ': 'Awaiting review',
  'ต้องใช้แอดมินอีกคน': 'Needs another admin',
  'แอดมินที่ไม่ได้แก้ร่างเป็นผู้เผยแพร่': "An admin who didn't edit the draft publishes it",
  'ตรวจรายการถัดไป →': 'Review the next one →',
  'ไม่มีงานค้าง': 'Nothing pending',
  'ร่างที่ยังไม่เคยเผยแพร่': 'Drafts never published',
  'ยังไม่อยู่ในแอป': 'Not in the apps yet',
  '{0} ร่าง': '{0} drafts',
  'ดูร่างทั้งหมด': 'View all drafts',
  'เพิ่มสถานีด่วน': 'Quick add station',
  'สถานะแค็ตตาล็อก': 'Catalog status',
  'รายการสถานี': 'Station list',
  ' · ค้นหา “{0}”': ' · search “{0}”',
  'กรองตามสถานะ': 'Filter by status',
  'ไม่พบสถานีชื่อ “{0}”': 'No station named “{0}”',
  'ยังไม่มีสถานี': 'No stations yet',
  'ไม่มีสถานีที่{0}': 'No stations in “{0}”',
  'ตรวจ': 'Review',
  'แก้ไข': 'Edit',
  'ค้นหาชื่อสถานี': 'Search station names',
  'เลื่อน': 'move',
  'เลือกสถานีจากรายการทางซ้าย': 'Pick a station from the list on the left',
  '{0} สถานี · เผยแพร่ {1} · รอตรวจ {2} · ร่าง {3}': '{0} stations · {1} published · {2} awaiting review · {3} drafts',
  'ภาษา / แนว': 'Language / genre',
  'สถานะ': 'Status',
  'สิทธิ์': 'Rights',
  'สตรีม': 'Stream',
  'แก้ไขล่าสุด': 'Last edited',
  'การทำงาน': 'Actions',
  'สถานีวิทยุ · Presets': 'Radio stations · Presets',
  'เล่นได้ · {0} ms': 'Plays · {0} ms',
  'ตรวจไม่ผ่าน · {0}': 'Failed check · {0}',
  'เพิ่งตรวจไปไม่ถึงนาที รอสักครู่แล้วลองใหม่': 'Checked less than a minute ago. Wait a moment and try again.',
  'บัญชีนี้ไม่มีสิทธิ์ตรวจสตรีม': "This account can't check streams",
  'ตรวจไม่ได้ในขณะนี้ ลองอีกครั้ง': "Couldn't check right now. Try again.",
  'สุขภาพสตรีม': 'Stream health',
  'สตรีมเล่นได้ไหม': 'Does the stream play?',
  'ระบบตรวจสตรีมที่เผยแพร่เป็นรอบ ๆ ยังไม่มีผลตั้งแต่เผยแพร่ครั้งล่าสุด': 'Published streams are checked on a schedule. No result since the last publish yet.',
  'ยังไม่เผยแพร่ ระบบจะเริ่มตรวจหลังเผยแพร่': 'Not published yet. Checks start after publishing.',
  'ตรวจไม่ผ่านติดกัน 3 ครั้ง ระบบไม่ปิดสถานีเอง ให้แอดมินดูว่าควรแก้ที่อยู่สตรีมหรือปิดสถานีชั่วคราว': "Failed 3 checks in a row. The station isn't disabled automatically; an admin should decide whether to fix the stream address or disable the station for now.",
  ' · ไม่ผ่าน {0} ครั้งติด': ' · failed {0} in a row',
  'ตรวจล่าสุด {0}': 'Last checked {0}',
  'กำลังตรวจ…': 'Checking…',
  'ตรวจตอนนี้': 'Check now',
  'ดูแค่ส่วนหัวและข้อมูลช่วงแรก ไม่เกิน 10 วินาที': 'Reads only the headers and the first data, up to 10 seconds',
  'ประวัติการตรวจ {0} ครั้งล่าสุด': 'Last {0} checks',
  'เผยแพร่': 'Publish',
  'หลักฐานนี้ถูกเพิกถอนไปแล้ว': 'This evidence was already revoked',
  'บัญชีนี้ไม่มีสิทธิ์จัดการหลักฐานสิทธิ์': "This account can't manage rights evidence",
  'ไม่พบสถานีหรือหลักฐานนี้': 'Station or evidence not found',
  '{0} ยังไม่ได้บันทึก': '{0} Nothing was saved.',
  'ระบบไม่พร้อมใช้งานชั่วคราว ยังไม่ได้บันทึก': 'The system is temporarily unavailable. Nothing was saved.',
  'เชื่อมต่อระบบไม่ได้ ยังไม่ได้บันทึก ลองอีกครั้ง': "Couldn't reach the system. Nothing was saved; try again.",
  'เพิ่มหลักฐานสิทธิ์แล้ว มีผลทันที': 'Rights evidence added. It applies right away.',
  'เพิกถอนแล้ว ถ้าไม่มีหลักฐานอื่นครอบคลุม แอปจะไม่เห็นสถานีนี้ทันที': 'Revoked. If no other evidence covers it, the apps stop showing this station right away.',
  'หลักฐานสิทธิ์': 'Rights evidence',
  ' ถึง {0}': ' until {0}',
  ' ไม่มีวันหมดอายุ': ', no expiry',
  ' · ประเทศ {0}': ' · country {0}',
  'โหลดหลักฐานสิทธิ์ไม่ได้ ลองโหลดหน้าใหม่': "Couldn't load the rights evidence. Try reloading the page.",
  'ยังไม่มีหลักฐานสิทธิ์ ต้องมีอย่างน้อยหนึ่งรายการที่ครอบคลุมประเทศของสถานีจึงจะเผยแพร่ได้': "No rights evidence yet. Publishing needs at least one record that covers the station's country.",
  'ไม่มีวันหมดอายุ': 'No expiry',
  'เพิ่มโดย {0}': 'Added by {0}',
  'ย้ายมาจากข้อมูลเดิม': 'Migrated from earlier data',
  'เพิกถอนโดย {0}': 'Revoked by {0}',
  'เพิกถอน': 'Revoke',
  '{0} (บันทึกใน audit)': '{0} (recorded in audit)',
  'ยืนยันเพิกถอน': 'Confirm revoke',
  'เพิ่มหลักฐานสิทธิ์': 'Add rights evidence',
  'เช่น บริษัทเจ้าของสถานี': "e.g. the station's owning company",
  '— เลือก —': '— Choose —',
  'เช่น เลขสัญญา หรือเลขตั๋ว': 'e.g. contract or ticket number',
  '{0} (บรรทัดละหนึ่ง ไม่บังคับ)': '{0} (one per line, optional)',
  'ใส่รหัสไฟล์ในที่เก็บส่วนตัวเท่านั้น ห้ามใส่ลิงก์ รหัสนี้ไม่ถูกส่งไปที่แอป': 'Enter private storage file keys only, no links. These keys never reach the apps.',
  'กำลังบันทึก…': 'Saving…',
  'เพิ่มหลักฐาน': 'Add evidence',
  'บัญชีนี้ไม่มีสิทธิ์ทำรายการนี้': "This account can't do this",
  'บันทึกร่างแล้ว · revision {0}': 'Draft saved · revision {0}',
  'เผยแพร่ revision {0} แล้ว แอปจะเห็นในการโหลดรายการครั้งถัดไป': 'Published revision {0}. The apps will see it the next time they load the list.',
  'ปิดสถานีแล้ว แอปจะไม่เห็นสถานีนี้': "Station disabled. The apps won't see it.",
  'เปิดสถานีอีกครั้งแล้ว': 'Station re-enabled',
  'เพิ่มสถานี': 'Add station',
  'ร่าง revision {0}': 'Draft revision {0}',
  ' · เผยแพร่ revision {0} เมื่อ {1}': ' · published revision {0} on {1}',
  'มีคนแก้สถานีนี้ไปก่อนแล้ว (ตอนนี้เป็น revision {0}) ค่าที่คุณแก้ยังไม่ได้บันทึก': "Someone else changed this station first (now revision {0}). Your edits weren't saved.",
  'โหลดค่าล่าสุด': 'Load the latest',
  'ข้อมูลสถานี': 'Station details',
  'สร้างร่างก่อน แล้วเพิ่มหลักฐานสิทธิ์ในหน้าสถานี': 'Create the draft first, then add rights evidence on the station page.',
  'บันทึกร่าง': 'Save draft',
  'สร้างร่าง': 'Create draft',
  'แก้ไข {0} ช่อง ยังไม่บันทึก': '{0} fields changed, not saved',
  'ไม่มีอะไรเปลี่ยน': 'No changes',
  'เปลี่ยนจากที่เผยแพร่': 'Changes from published',
  'เปลี่ยนจาก revision {0} ที่เผยแพร่อยู่': 'Changes from published revision {0}',
  'บันทึกร่างก่อน แล้วให้แอดมินอีกคนตรวจและเผยแพร่': 'Save the draft first, then have another admin review and publish it.',
  'กรณีฉุกเฉิน: เผยแพร่โดยไม่มีแอดมินคนที่สอง': 'Emergency: publish without a second admin',
  'ใช้เมื่อรอแอดมินคนอื่นไม่ได้ เช่น ลิงก์สตรีมเสียและผู้ฟังเล่นไม่ได้ ต้องยืนยัน MFA ภายใน 5 นาที รายการนี้บันทึกใน audit แยกเป็น “เผยแพร่แบบฉุกเฉิน” เพื่อให้ทีมตรวจย้อนหลัง': "Use this only when you can't wait for another admin, e.g. the stream link is broken and listeners can't play it. Needs MFA within 5 minutes. It is recorded in audit as an “emergency publish” for the team to review later.",
  'เหตุผลที่ต้องเผยแพร่ทันที (อย่างน้อย 20 ตัวอักษร)': 'Why this must be published now (at least 20 characters)',
  'ฉันตรวจร่างนี้แล้ว และเข้าใจว่าไม่มีผู้ตรวจคนที่สอง': 'I reviewed this draft and understand there is no second reviewer',
  'เผยแพร่ฉุกเฉิน revision {0}': 'Emergency publish revision {0}',
  'มีหลักฐานสิทธิ์ที่ใช้งานอยู่และครอบคลุมประเทศ {0}': 'Active rights evidence covers country {0}',
  'คุณไม่ได้แก้ร่างนี้เอง': "You didn't edit this draft yourself",
  'เหตุผลที่เผยแพร่ (บันทึกใน audit)': 'Reason for publishing (recorded in audit)',
  'เผยแพร่ revision {0}': 'Publish revision {0}',
  'เปิดหรือปิดสถานี': 'Enable or disable station',
  'สถานีถูกปิดอยู่': 'Station is disabled',
  'ปิดสถานีชั่วคราว': 'Disable station temporarily',
  'ปิดเมื่อ {0} แอปมองไม่เห็นสถานีนี้': "Disabled on {0}. The apps can't see this station.",
  'แอปจะไม่เห็นสถานีนี้จนกว่าจะเปิดอีกครั้ง': "The apps won't see this station until it is re-enabled.",
  'เหตุผลที่เปิด (บันทึกใน audit)': 'Reason for enabling (recorded in audit)',
  'เหตุผลที่ปิด (บันทึกใน audit)': 'Reason for disabling (recorded in audit)',
  'ดั้งเดิม': 'Classic',
  'การ์ดกลางจอ เมนูด้านบน แบบที่ใช้มาตลอด': 'A card in the middle, menu on top: the layout used so far',
  'ผนังวิทยุส่วนตัว': 'Personal radio wall',
  'เมนูด้านข้าง หน้าแรกเป็นผนังปุ่มสถานี ตัวเล่นเป็นแถบล่างทุกหน้า': 'Side menu, a home page of station buttons, a player bar along the bottom of every page',
  'เฉพาะแอดมินเท่านั้นที่เปลี่ยนธีมของเว็บได้': "Only admins can change the web app's theme",
  'ธีมของเว็บผู้ใช้': "The web app's theme",
  'โครงหน้าที่ผู้ใช้ทุกคนเห็นบนคอมพิวเตอร์ ผู้ใช้เปลี่ยนเองไม่ได้ เลือกได้แค่สีในหน้าการตั้งค่าของตัวเอง มือถือใช้แบบเดียวทุกธีม': 'The layout every user sees on a computer. Users cannot change it; they choose only a colour on their own settings page. Phones keep one layout whatever the theme.',
  'เปลี่ยนล่าสุดโดย {0} · {1}': 'Last changed by {0} · {1}',
  'บันทึกแล้ว ผู้ใช้จะเห็นธีมใหม่ภายในประมาณหนึ่งนาที': 'Saved. Users will see the new theme within about a minute.',
  'ใช้ธีมนี้กับผู้ใช้ทุกคน': 'Use this theme for every user',
  'ผนังพรีเซ็ต': 'Preset wall',
  'เมนูด้านบน ปุ่มสถานีสี่คอลัมน์ พร้อมพื้นที่ค้นพบวิทยุข้างกัน': 'Top navigation, four columns of stations and a discovery area beside them',
  'ชั้นวางฟังเพลง': 'Listening shelves',
  'เมนูด้านข้าง ชั้นสถานีโปรด ฟังล่าสุด และยอดนิยมในประเทศที่เลือก': 'Side navigation with favorites, recently played and popular stations in the chosen country',
  'สตูดิโอ': 'Studio',
  'เมนูด้านข้าง การ์ดสถานีเด่นสามใบ และชั้นสถานีในพื้นที่สว่าง': 'Side navigation, up to three station highlights and shelves on a light canvas',
  'แบบดั้งเดิม': 'Classic layout',
  'แบบของ Claude': 'Claude designs',
  'แบบของ Codex': 'Codex designs',
  'ออกแบบร่วมกัน': 'Joint designs',
  'ชุดสตูดิโอและเวที': 'Studio and stage designs',
};
